framework:
    assets:
        # Base path for assets (empty = root)
        base_path: ''
        # Packages configuration
        packages:
            # Default package
            _default:
                version_strategy: null
                version: null
                version_format: '%%s?%%s'
                json_manifest_path: null
                base_path: ''

